[package]
name = "pixel-renerer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glam = "0.24.2"
pixels = "0.13.0"
winit = { version = "0.29.4", features = ["rwh_05"] }
